<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>glsp</string>
	</array>
	<key>name</key>
	<string>GameLisp</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>r(#*)"</string>
			<key>end</key>
			<string>"\1</string>
			<key>name</key>
			<string>string.quoted.double.raw.glsp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>(?&lt;!\\)"</string>
			<key>name</key>
			<string>string.quoted.double.glsp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;!{){(?!{)</string>
					<key>end</key>
					<string>(?&lt;!})}(?!})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\\(space|tab|newline|return|nul)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.other.glsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\x[0-7]\h</string>
			<key>name</key>
			<string>constant.numeric.integer.other.glsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\u{\h\h?\h?\h?\h?\h?}</string>
			<key>name</key>
			<string>constant.numeric.integer.other.glsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.numeric.integer.other.glsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-?[\d_]*\d[\d_]*\b</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.glsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>0b[01_]*[01][01_]*\b</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.glsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>0o[0-7_]*[0-7][0-7_]*\b</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.glsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>0x[\h_]*\h[\h_]*\b</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.glsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#(t|f|n)\b</string>
			<key>name</key>
			<string>constant.language.glsp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.glsp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\()(def|defn|defmacro|defclass|defmixin|defstruct|state\*|state|fsm|load|require)\b(?!-)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.glsp keyword.declaration.other.glsp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\()(let|let-fn|let-macro|let-class|let-mixin|fn0|fn1|fn|field|const|prop|wrap-prop|met|wrap|init-state|init-mixin|init|fini-state|fini-mixin|fini|mixin)\b(?!-)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.glsp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\()(if|when|unless|while|until|cond==|cond-eq\?|cond-same\?|cond|return|yield|else|any-of|forni|forn|for|block|restart-block|finish-block|in|do|break|continue|\@base|\@enab!|\@enab\?|\@disab!|enab!|enab\?|disab!|match|matches\?|when-let)\b(?!-)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(</string>
			<key>name</key>
			<string>punctuation.section.parens.begin.glsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\)</string>
			<key>name</key>
			<string>punctuation.section.parens.end.glsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.line.glsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#\;</string>
			<key>name</key>
			<string>comment.block.glsp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#\|</string>
			<key>end</key>
			<string>\|\#</string>
			<key>name</key>
			<string>comment.block.glsp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comment</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-comment</key>
		<dict>
			<key>begin</key>
			<string>\#\|</string>
			<key>end</key>
			<string>\|\#</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comment</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.glsp</string>
</dict>
</plist>
